name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: pulling git repo
        uses: actions/checkout@v4

      - name: Install Python version 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt


  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      environment:
        name: prod
      steps:

        - name: pulling git repo
          uses: actions/checkout@v4

        - name: deploy to ubuntu server
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{secrets.PROD_HOST}}
            username: ${{secrets.PROD_USERNAME}}
            password: ${{secrets.PROD_PASSWORD}}
            script: |
              cd app/src
              git pull
               echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart gunicorn
        # login to our ubuntu
        # cd /app/src
        # git pull
        # systemctl restart api
